// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/40f2dd30cfbcd339e45d7c2fa92ecbe8b743aa97/soap/soap.d.ts
// Type definitions for soap
// Project: https://www.npmjs.com/package/soap
// Definitions by: Nicole Wang <https://github.com/nicoleWjie>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

// @a8775 added BasicAuthSecurity class

declare module 'soap' {
    import * as events from 'events';

    class WSSecurity {
        constructor(username: string, password: string, options: any);
    }
    class BasicAuthSecurity {
        constructor(username: string, password: string);
    }
    interface Client extends events.EventEmitter {
        setSecurity(s: WSSecurity): void;
        [method: string]: (args: any, fn: (err: any, result: any) => void, options?: any) => void;
        addSoapHeader(headJSON: any): void;
    }
    function createClient(wsdlPath: string, options: any, fn: (err: any, client: Client) => void): void;

}